version: "3.5"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "10010:10010"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "10020:3000"
