version: "3.5"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    network_mode: host
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    network_mode: host