version: "3.5"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    volumes:
      - "./backend/profiles:/app/profiles"
      - "./backend/recordings:/app/recordings"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    network_mode: host